# Nodejs version
FROM node:17

# Set the working directory
WORKDIR /app

# Copy package.json 
COPY package*.json ./

# Install dependencies
RUN npm install

# Copying the rest of applciations
COPY . .

# Run tests
CMD ["npm", "test"]
